SUMMARY = "Hello World by Cargo for Rust"
LICENSE = "CLOSED"

inherit cargo pkgconfig

DEPENDS += "alsa-lib"

BASE_SRC_URI = "/home/rob/workplace/neutron/app"
SRC_URI = "file://${BASE_SRC_URI};protocol=file"
SRCREV = "main"
S = "${WORKDIR}/${BASE_SRC_URI}"

BBCLASSEXTEND = "native"
BB_STRICT_CHECKSUM = "0"

# THE FOLLOWING WAS AUTO_GENERATED BY cargo-bitbake

# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/aho-corasick/1.1.3 \
    crate://crates.io/alsa-sys/0.3.1 \
    crate://crates.io/alsa/0.9.1 \
    crate://crates.io/anyhow/1.0.95 \
    crate://crates.io/autocfg/1.4.0 \
    crate://crates.io/bindgen/0.70.1 \
    crate://crates.io/bitflags/1.3.2 \
    crate://crates.io/bitflags/2.6.0 \
    crate://crates.io/bumpalo/3.16.0 \
    crate://crates.io/bytes/1.9.0 \
    crate://crates.io/cc/1.2.7 \
    crate://crates.io/cesu8/1.1.0 \
    crate://crates.io/cexpr/0.6.0 \
    crate://crates.io/cfg-if/1.0.0 \
    crate://crates.io/clang-sys/1.8.1 \
    crate://crates.io/combine/4.6.7 \
    crate://crates.io/core-foundation-sys/0.8.7 \
    crate://crates.io/coreaudio-rs/0.11.3 \
    crate://crates.io/coreaudio-sys/0.2.16 \
    crate://crates.io/cpal/0.15.3 \
    crate://crates.io/dasp_sample/0.11.0 \
    crate://crates.io/either/1.13.0 \
    crate://crates.io/equivalent/1.0.1 \
    crate://crates.io/glob/0.3.2 \
    crate://crates.io/hashbrown/0.15.2 \
    crate://crates.io/indexmap/2.7.0 \
    crate://crates.io/itertools/0.13.0 \
    crate://crates.io/jni-sys/0.3.0 \
    crate://crates.io/jni/0.21.1 \
    crate://crates.io/jobserver/0.1.32 \
    crate://crates.io/js-sys/0.3.76 \
    crate://crates.io/libc/0.2.169 \
    crate://crates.io/libloading/0.8.6 \
    crate://crates.io/log/0.4.22 \
    crate://crates.io/mach2/0.4.2 \
    crate://crates.io/memchr/2.7.4 \
    crate://crates.io/minimal-lexical/0.2.1 \
    crate://crates.io/ndk-context/0.1.1 \
    crate://crates.io/ndk-sys/0.5.0+25.2.9519653 \
    crate://crates.io/ndk/0.8.0 \
    crate://crates.io/nom/7.1.3 \
    crate://crates.io/num-derive/0.4.2 \
    crate://crates.io/num-traits/0.2.19 \
    crate://crates.io/num_enum/0.7.3 \
    crate://crates.io/num_enum_derive/0.7.3 \
    crate://crates.io/oboe-sys/0.6.1 \
    crate://crates.io/oboe/0.6.1 \
    crate://crates.io/once_cell/1.20.2 \
    crate://crates.io/pkg-config/0.3.31 \
    crate://crates.io/proc-macro-crate/3.2.0 \
    crate://crates.io/proc-macro2/1.0.92 \
    crate://crates.io/quote/1.0.38 \
    crate://crates.io/regex-automata/0.4.9 \
    crate://crates.io/regex-syntax/0.8.5 \
    crate://crates.io/regex/1.11.1 \
    crate://crates.io/rustc-hash/1.1.0 \
    crate://crates.io/same-file/1.0.6 \
    crate://crates.io/shlex/1.3.0 \
    crate://crates.io/syn/2.0.95 \
    crate://crates.io/thiserror-impl/1.0.69 \
    crate://crates.io/thiserror/1.0.69 \
    crate://crates.io/toml_datetime/0.6.8 \
    crate://crates.io/toml_edit/0.22.22 \
    crate://crates.io/unicode-ident/1.0.14 \
    crate://crates.io/walkdir/2.5.0 \
    crate://crates.io/wasm-bindgen-backend/0.2.99 \
    crate://crates.io/wasm-bindgen-futures/0.4.49 \
    crate://crates.io/wasm-bindgen-macro-support/0.2.99 \
    crate://crates.io/wasm-bindgen-macro/0.2.99 \
    crate://crates.io/wasm-bindgen-shared/0.2.99 \
    crate://crates.io/wasm-bindgen/0.2.99 \
    crate://crates.io/web-sys/0.3.76 \
    crate://crates.io/winapi-util/0.1.9 \
    crate://crates.io/windows-core/0.54.0 \
    crate://crates.io/windows-result/0.1.2 \
    crate://crates.io/windows-sys/0.45.0 \
    crate://crates.io/windows-sys/0.59.0 \
    crate://crates.io/windows-targets/0.42.2 \
    crate://crates.io/windows-targets/0.52.6 \
    crate://crates.io/windows/0.54.0 \
    crate://crates.io/windows_aarch64_gnullvm/0.42.2 \
    crate://crates.io/windows_aarch64_gnullvm/0.52.6 \
    crate://crates.io/windows_aarch64_msvc/0.42.2 \
    crate://crates.io/windows_aarch64_msvc/0.52.6 \
    crate://crates.io/windows_i686_gnu/0.42.2 \
    crate://crates.io/windows_i686_gnu/0.52.6 \
    crate://crates.io/windows_i686_gnullvm/0.52.6 \
    crate://crates.io/windows_i686_msvc/0.42.2 \
    crate://crates.io/windows_i686_msvc/0.52.6 \
    crate://crates.io/windows_x86_64_gnu/0.42.2 \
    crate://crates.io/windows_x86_64_gnu/0.52.6 \
    crate://crates.io/windows_x86_64_gnullvm/0.42.2 \
    crate://crates.io/windows_x86_64_gnullvm/0.52.6 \
    crate://crates.io/windows_x86_64_msvc/0.42.2 \
    crate://crates.io/windows_x86_64_msvc/0.52.6 \
    crate://crates.io/winnow/0.6.22 \
"

# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    "

SUMMARY = "neutron"
HOMEPAGE = "LOCAL"
LICENSE = "CLOSED"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include neutron-${PV}.inc
include neutron.inc
